/** 화면에 나오는 고정 문구를 한곳에 모은다. 말투 일관성을 위해서다. */
export const ui = {
  owlName: "노리",
  landingTitle: "AI쏙",
  landingSubtitle: "AI는 어떻게 생각할까?",
  landingCta: "시작하기",
  lessonDone: "끝냈어",
  lessonNext: "다음은 이거!",
  hookCta: "궁금해!",
  playDone: "다 했어요",
  nameCta: "알겠어!",
  challengeCorrect: "맞았어! 🎉",
  challengeRetry: "이렇게 되는 거야!",
  challengeNext: "다음으로",
  predictCta: "직접 확인해보자!",
  revealPicked: "네 생각:",
  revealRight: "네 말이 맞았어! 🎉",
  revealWrong: "어? 달랐네! 그게 재밌는 거야.",
  rewardTitle: "배지 획득!",
  rewardCta: "좋아!",
  lessonComplete: "레슨을 끝냈어!",
  lessonKeptLocally: "이 기기에 보관했어. 연결되면 내 방에도 저장할게!",
  soundOn: "소리 켜기",
  soundOff: "소리 끄기",
} as const;

export const badgeNames: Record<string, string> = {
  "map-explorer": "지도 탐험가",
  "path-finder": "길 찾기 대장",
  teacher: "꼬마 선생님",
  "gap-finder": "빈틈 탐정",
  "taste-reader": "취향 탐정",
  "pixel-hunter": "픽셀 사냥꾼",
  "sharp-eye": "매의 눈",
  "wave-rider": "소리 파도타기",
  "piece-master": "조각 박사",
  "bridge-builder": "다리 놓는 아이",
  "group-finder": "무리 찾기 대장",
  "word-math": "말 수학자",
  "meter-master": "저울 박사",
  "story-weaver": "이야기 짓는 아이",
  "feeling-judge": "기분 판사",
  "bit-master": "0과 1 마법사",
};

/** 계정과 내 방 화면의 문구. */
export const account = {
  joinTitle: "네 이름을 골라봐",
  joinOwl: "여기서 쓸 이름이야. 마음에 드는 걸 고르면 돼!",
  reroll: "다른 이름 보기",
  codeTitle: "비밀코드가 나왔어!",
  codeOwl: "이 코드가 있어야 다른 기기에서도 네 방에 들어올 수 있어.",
  codeWarning: "이 코드는 다시 볼 수 없어. 꼭 적어두거나 저장해!",
  saveImage: "그림으로 저장하기",
  toRoom: "내 방으로 가기",
  loginTitle: "내 방으로 들어가기",
  loginOwl: "이름을 고르고 비밀코드를 넣어줘.",
  loginCta: "들어가기",
  loginFailed: "이름이나 코드가 맞지 않아. 다시 해볼래?",
  loginThrottled: "너무 많이 시도했어. 잠깐 쉬었다가 다시 해줘.",
  nicknameFull: "그 이름은 자리가 찼어. 다른 이름을 골라줄래?",
  signupFailed: "방을 만들지 못했어. 잠시 뒤에 다시 해볼래?",
  roomTitle: "내 방",
  roomBadges: "모은 배지",
  roomNoBadges: "아직 배지가 없어. 레슨을 하나 끝내보자!",
  roomProgress: "끝낸 레슨",
  roomArtifacts: "내 작품",
  roomNoArtifacts: "아직 작품이 없어. 레슨에서 만든 게 여기 쌓여!",
  logout: "나가기",
  logoutFailed: "지금은 나갈 수 없어. 잠시 뒤에 다시 해볼래?",
  deleteRoom: "내 방 지우기",
  deleteRoomConfirm: "정말 지울까? 배지랑 작품이 전부 사라지고 되돌릴 수 없어.",
  deleteRoomYes: "응, 지울래",
  deleteRoomNo: "아니, 그대로 둘래",
  join: "내 방 만들기",
  login: "내 방 들어가기",
} as const;

/** 단어 실험실(/lab) 문구. 아이 화면이라 반말. */
export const lab = {
  title: "단어 실험실",
  door: "아무 단어나 넣어봐. 얼마나 비슷한지 컴퓨터가 잰다!",
  introOwl: "고양이랑 강아지, 얼마나 비슷할까? 먼저 찍어봐!",
  introChoices: ["별로 안 비슷해", "좀 비슷해", "아주 비슷해"],
  introReveal: "컴퓨터가 잰 값이야. 이제 네가 아무 단어나 넣어봐!",
  note: "이건 이 모델이 비슷하다고 본 정도야. 말뜻의 정답은 아니야.",
  compareTitle: "두 단어 비교",
  compareHint: "한쪽만 바꿔봐. 아까 잰 건 아래에 남아.",
  score: "닮은 정도",
  history: "아까 잰 것",
  nearTitle: "가까운 말",
  nearHint: "단어 하나를 고르면 가까운 말 20개가 나와. 눌러서 따라가 봐.",
  placeholder: "단어를 쳐봐",
  star: "남기기",
  starred: "남겼어",
  save: "내 방에 넣기",
  saved: "내 방에 넣었어!",
  saveGuest: "방을 만들면 발견을 남길 수 있어",
  saveFailed: "지금은 못 넣었어. 잠시 뒤에 다시 해볼래?",
  challengesTitle: "해볼래?",
  challenges: [
    "강아지랑 80 넘게 나오는 단어를 찾아봐",
    "동물인데 강아지랑 60 아래인 걸 찾아봐",
    "가까운 말 1등이 뭘지 먼저 찍고 확인해봐",
  ],
  loadFailed: "지금은 잴 수 없어. 잠시 뒤에 다시 해볼래?",
} as const;

/** 오늘의 단어(/daily) 문구. 아이 화면이라 반말. */
export const daily = {
  title: "오늘의 단어",
  door: "숨은 단어를 맞혀봐. 넣을 때마다 얼마나 가까운지 알려줘!",
  owl: "오늘의 단어가 숨어 있어. 아무 단어나 넣어봐. 가까울수록 뜨거워져!",
  note: "점수는 이 모델이 비슷하다고 본 정도야. 말뜻의 정답은 아니야.",
  guessLabel: "넣을 단어",
  temperature: {
    correct: "정답! 🎉",
    hot: "뜨거워 🔥",
    warm: "따뜻해 ☀️",
    lukewarm: "미지근해 🌤️",
    cold: "차가워 ❄️",
  },
  rankInside: (rank: number) => `${rank}위`,
  rankOutside: "1000위 밖",
  tries: (n: number) => `${n}번 넣었어`,
  solvedTitle: "맞혔어!",
  solvedBody: (tries: number) => `${tries}번 만에 맞혔어. 내일 또 새 단어가 나와!`,
  hint: "힌트 볼래?",
  noWord: "오늘은 단어가 준비 안 됐어. 내일 다시 와줘!",
  boardTitle: "오늘 순위",
  boardSolved: (n: number) => `오늘 ${n}명이 맞혔어`,
  boardMe: (rank: number, total: number) => `나: ${total}명 중 ${rank}등`,
  boardGuest: "방을 만들면 순위에 올라가",
  boardHintMark: "💡",
  yesterdayTitle: "어제 판",
  yesterdayAnswer: (word: string) => `어제 단어는 "${word}"였어`,
  yesterdayPopular: "아이들이 많이 넣은 말",
  yesterdayWhy: "왜 이 말들이 가까웠을까? 실험실에서 재봐!",
  toLab: "단어 실험실로",
  loadFailed: "지금은 잴 수 없어. 잠시 뒤에 다시 해볼래?",
  roomStreak: (days: number) => `연속 ${days}일 참여`,
  roomBest: (tries: number) => `최소 ${tries}번 만에 정답`,
} as const;
